
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install -g @angular/cli
      - npm install -g yarn
      - git fetch --all
      - yarn install
      - yarn nx affected --target=test --base=origin/develop
      - yarn nx affected --target=lint --base=origin/develop
  build:
    commands:
      - yarn nx affected --target=build --base=origin/develop --configuration=dev
