
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install -g @angular/cli
      - npm install -g yarn
      - git fetch --all
      - yarn install
      - yarn nx affected --target=test --base=$GIT_BASE
      - yarn nx affected --target=lint --base=$GIT_BASE
  build:
    commands:
      - yarn nx affected --target=build --base=$GIT_BASE --configuration=$BUILD_CONFIGURATION
