version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install -g @angular/cli
      - npm install -g yarn
      - yarn install
      - yarn nx affected --target=test --base=HEAD~
      - yarn nx affected --target=lint --base=HEAD~
  build:
    commands:
      - yarn nx affected --target=build --base=HEAD~ --configuration=$BUILD_CONFIGURATION
  # post_build:
  #   commands:
  #     - aws s3 rm $S3_BUCKET --recursive
artifacts:
  files:
    - '**/*'
  name: artifact-name
  base-directory: 'dist'
  discard-paths: no
