version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install -g @angular/cli
      - npm install -g yarn
      - git fetch --all
      - yarn install
      - yarn nx affected --target=test --base=$GIT_BASE
      - yarn nx affected --target=lint --base=$GIT_BASE
  build:
    commands:
      - yarn nx affected --target=build --base=$GIT_BASE --configuration=$BUILD_CONFIGURATION
  # post_build:
  #   commands:
  #     - aws s3 rm $S3_BUCKET --recursive
artifacts:
  files:
    - '**/*'
  name: artifact-name
  base-directory: 'dist'
  discard-paths: no
